### ISSUE TITLE
Windows Mobile Hotspot Adapter

### ISSUE THREAD

**Issue by Nerixyz** [librespot-org/libmdns#20]
When registering a service, the service won't respond to mDNS on packets from the Mobile Hotspot / Wi-Fi Direct network adapter.
I assume this is because it only listenes on the "main" interface. 

Furthermore, I noticed, packets from an Android emulator (in my case Genymotion, using Virtual-Box under the hood) won't come through either.

**Comment by sashahilton00** [comment]
For the Wifi hotspot, I have no idea if that offers a compliant implementation that this library would work with. Also, I believe the hotspot runs its own DHCP server, which this library wouldn't detect or advertise on.

For Genymotion, I was under the impression that it uses some sort of bridge/loopback interface, which again is unlikely to work on the host machine. You might be able to toggle a setting somewhere that stops network bridging and advertises as a seperate device on the network, but I'm not familiar enough with it to be able to tell you if that is the case for sure.

**Comment by willstott101** [comment]
Dongles and hotspot adapters will likely impoved by `0.7.3` where we addressed #33 

Dongles plugged in after the Responder starts won't work, but starting libmdns after the dongle is connected should now work, provided the issue was the computer having multiple network interfaces and the OS choosing one other than the one you wanted to use.

Closing as maybe-fixed, re-open if you try again and still have issues.
